CREATE TABLE THEATRE (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE SCREEN (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  THEATRE_ID INTEGER REFERENCES THEATRE(ID),
  NUMBER_OF_ROWS INTEGER NOT NULL,
  NUMBER_OF_COLUMNS INTEGER NOT NULL
);

CREATE TABLE SHOW (
  ID SERIAL PRIMARY KEY,
  DATE DATE NOT NULL,
  TIME TIME NOT NULL,
  MOVIE_ID INTEGER REFERENCES MOVIE(ID),
  SCREEN_ID INTEGER REFERENCES SCREEN(ID)
);

CREATE TABLE TRANSACTION (
  ID SERIAL PRIMARY KEY,
  EMAIL_ID VARCHAR(255) NOT NULL,
  BOOKING_REF_NUMBER VARCHAR(255),
  SHOW_ID INTEGER REFERENCES SHOW(id),
  PAYMENT_TYPE VARCHAR(255),
  IS_CANCELLED BOOLEAN
);

CREATE TABLE TRANSACTION_SEATS (
  TRANSACTION_ID INTEGER REFERENCES TRANSACTION(ID),
  SEAT_NUMBER VARCHAR(10)
);

INSERT INTO THEATRE(name) VALUES ('PVR');
INSERT INTO THEATRE(name) VALUES ('INOX');
INSERT INTO THEATRE(name) VALUES ('FUN');
INSERT INTO THEATRE(name) VALUES ('LIDO');
INSERT INTO THEATRE(name) VALUES ('CITY PRIDE');

INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 1', 1, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 2', 1, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 1', 2, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 2', 2, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 1', 3, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 2', 3, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 1', 4, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 2', 4, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 1', 5, 26, 10);
INSERT INTO SCREEN(name, THEATRE_ID, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS) VALUES ('Screen 2', 5, 26, 10);

INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-14', '09:00:00', 1, 1);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-14', '12:00:00', 2, 2);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-14', '20:00:00', 3, 3);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-15', '01:00:00', 4, 4);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-15', '09:00:00', 5, 5);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-15', '12:00:00', 6, 6);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-03-14', '03:00:00', 7, 7);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-03-14', '04:00:00', 1, 8);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-03-14', '06:00:00', 2, 1);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-24', '09:00:00', 3, 2);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-25', '08:00:00', 4, 3);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-26', '10:00:00', 5, 4);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-23', '19:00:00', 6, 5);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-04-14', '23:00:00', 7, 6);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-03-01', '18:00:00', 1, 7);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-02', '13:00:00', 3, 8);
INSERT INTO SHOW(DATE, TIME, MOVIE_ID, SCREEN_ID) VALUES ('2019-02-23', '09:00:00', 4, 1);
